### ISSUE TITLE
Non-static support

### ISSUE THREAD

**Issue by justincy** [justincy/nextjs-domain-locales#4]
Due to #3 and the fact that we plan on using next-i18next (which doesn't support static pages anyway), we're going to give up on supporting static pages for now and focus on just getting SSR working with `getInitialProps()`.

We'll get rid of the dynamic `[locale]` directory and just detect the lang in middleware, setting the value on the `req` object, and somehow use that value to instantiate i18n.

TODO: 

* [x] Remove `[locale]` dynamic dir
* [x] Lookup locale and set on ~~`req`~~ query
* [x] Use locale from query to instantiate i18n
* [x] Render in other langs
* [x] Fix language detection on the server

**Comment by justincy** [comment]
Domain routing with next-i18next: https://github.com/isaachinman/next-i18next/issues/16#issuecomment-520853281

**Comment by justincy** [comment]
Based on the link above, I was able to get this working. But it's not ideal yet. It looks like it's always rendering in English on the server and then detecting the correct lang on the browser and updating the language. 

Maybe there's a bug in the language detection in the server.

**Comment by justincy** [comment]
The header I was relying on for the hostname was express specific. I fixed it to work without express.

**Comment by bitsmyth** [comment]
Hey I came across your repo and just wanted to provide some input for you.

By [adding getInitialProps() to the _app file ](https://nextjs.org/docs/advanced-features/custom-app#caveats) you will disable automatic static generation. For my understanding, your entire project will run SSR, which is not ideal if you have static sites, in matter of fact you will be paying for something what otherwise would come free.

A better aproach would be to detect the language in `_app.jsx` just on the clientside with `useEffect()` so you can have the automatic static feature enabled and open a modal with the different language options if the detected language is different from the displayed one. From that point the user can decide what he wants to view.

Disclaimer
I dont know if this is possible with `next-i18next` as I am currently searching for a solution I described above.

**Comment by justincy** [comment]
That could work if you're okay with not having any text shown until the language is detected and the translation strings are loaded. I also don't know whether it could be done with `next-i18next`. Let me know what you find out.
